### ISSUE TITLE
Add array introduction and array operations.

### ISSUE THREAD

**Issue by subhamengine** [subhamengine/DataStructures-and-Algorithm#2]
path:- subhamengine/DataStructures-and-Algorithm/DataStructure/c++/Array

**Comment by siddharthgangwar25** [comment]
Hey! Can you assign it to me?

**Comment by subhamengine** [comment]
go for it

**Comment by HackX-OP** [comment]
Can I work on it,I will ad basic array programes such as  searching,updation , insert and delete.

**Comment by subhamengine** [comment]
Nice work!
