### ISSUE TITLE
Add array operations like Introduction and all basic concepts . path -  DataStructures-and-Algorithm/ DataStructures/c++/array

### ISSUE THREAD

**Issue by subhamengine** [subhamengine/DataStructures-and-Algorithm#4]
also create a readme.md file for the array folder

**Comment by scmishra-cse** [comment]
Okay

**Comment by subhamengine** [comment]
go for it @scmishra-cse

**Comment by schmelto** [comment]
if you want to include this in `hactoberfest` you schould chagne the label from `for hacktoberfest` to `hacktoberfest`
